version: "3.9"
services:
  django-app:
    container_name: django-app-continer
    env_file:
      - ./.env
    build: .
    volumes:
      - .:/code:ro
    ports:
      - "8000:8000"
    entrypoint: ./start.sh


